name: Develop PR 

on:
  pull_request:
    branches: [ develop ]

jobs:
  terraform-validate-and-plan:
    name: Validate and Plan TF
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Install terragrunt CLI
        run: |
          echo 'Installing terragrunt now'
          brew install terragrunt

      - name: Terragrunt Plan
        id: plan
        run: terragrunt plan --terragrunt-non-interactive