name: Deploy Terraform

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform-validate-and-plan:
    name: Validate and Plan TF
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
